package com.travelplan.travel.repository;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * Raw {@code TRANSPORT} relationship, as read directly from Neo4j by
 * {@link TransportRepository} — one hop, whether from a one-hop traversal
 * ({@code findActiveOutgoing}), an update, or one leg of a multi-hop
 * pathfinding result ({@code findShortestPath}).
 *
 * Not an API type: {@code TransportService} maps this to
 * {@link com.travelplan.travel.dto.TransportResponse} or
 * {@link com.travelplan.travel.dto.RouteHop}.
 *
 * {@code id} (docs/lets-travel-architecture-decisions.md §11 addendum) is the
 * relationship's own application-assigned identifier — a UUID stored as a
 * relationship property, generated by {@code TransportService} at creation
 * time, never Neo4j's internal (opaque) element id. Added after the initial
 * increment 2 shape; purely additive.
 */
public record TransportEdge(UUID id, String mode, int durationMinutes, OffsetDateTime departureTime,
                             OffsetDateTime arrivalTime, UUID targetId, String targetName,
                             String targetCountry) {
}
