-- V7__add_refresh_tokens.sql
-- Refresh token support (previously an assumed gap — see JwtService's class
-- Javadoc before this migration: "No refresh token, no revocation/blacklist").
--
-- A refresh token is an opaque, high-entropy random value — never a JWT —
-- generated by RefreshTokenService and returned to the client exactly once,
-- at issuance. Only its SHA-256 hash is ever persisted here, same principle
-- as `users.password_hash`: this table's rows are useless to an attacker who
-- reads the database, and the raw value is never logged or otherwise stored.
--
-- Same soft-delete pattern as `users`/`reports`: deleted_at, never a physical
-- delete. Here deleted_at doubles as "revoked": a token is soft-deleted both
-- on logout and on successful use (rotation — refresh is single-use, a
-- replayed token is rejected exactly like an unknown one, same
-- non-disclosure principle AuthService already applies to login/GET /me).
-- expires_at is checked at the application layer (RefreshTokenService), not
-- by a DB constraint — consistent with `reports.status`'s transition rules
-- living in ReportService, not in SQL.

CREATE TABLE refresh_tokens (
    id          UUID        NOT NULL DEFAULT gen_random_uuid(),
    user_id     UUID        NOT NULL,
    token_hash  TEXT        NOT NULL,
    expires_at  TIMESTAMPTZ NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at  TIMESTAMPTZ,

    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id)
);

-- Backs the redeem-by-hash lookup on every POST /refresh; also the
-- collision check implicit in a UNIQUE index (astronomically unlikely for a
-- 256-bit random value, enforced anyway — cheap insurance, same reasoning as
-- other surrogate-id uniqueness constraints in this project).
CREATE UNIQUE INDEX idx_refresh_tokens_token_hash ON refresh_tokens (token_hash);

-- Not queried by today's endpoints (no "revoke all of this user's sessions"
-- yet), but the natural index for that future addition — cheap to add now,
-- alongside the table itself.
CREATE INDEX idx_refresh_tokens_user_id_active
    ON refresh_tokens (user_id)
 WHERE deleted_at IS NULL;
